UR5E_ROBOTIQ_CONSTANTS=dict(
    name="ur5e_robotiq",
    all_joint_names=[
        #"ur5e_0_base_joint", 
        "ur5e_0_shoulder_pan_joint",
        "ur5e_0_shoulder_lift_joint",
        "ur5e_0_elbow_joint",
        "ur5e_0_wrist_1_joint",
        "ur5e_0_wrist_2_joint",
        "ur5e_0_wrist_3_joint",

        ],
    ik_joint_names=[
        #"ur5e_0_base_joint", 
        "ur5e_0_shoulder_pan_joint",
        "ur5e_0_shoulder_lift_joint",
        "ur5e_0_elbow_joint",
        "ur5e_0_wrist_1_joint",
        "ur5e_0_wrist_2_joint",
        "ur5e_0_wrist_3_joint",
    ],
    arm_joint_names=[
        "ur5e_0_shoulder_pan_joint",
        "ur5e_0_shoulder_lift_joint",
        "ur5e_0_elbow_joint",
        "ur5e_0_wrist_1_joint",
        "ur5e_0_wrist_2_joint",
        "ur5e_0_wrist_3_joint",
        ],
    actuator_info={
        #"ur5e_0_base_joint": "ur5e_0_base",
        "ur5e_0_shoulder_pan_joint": "ur5e_0_shoulder_pan",
        "ur5e_0_shoulder_lift_joint": "ur5e_0_shoulder_lift",
        "ur5e_0_elbow_joint": "ur5e_0_elbow",
        "ur5e_0_wrist_1_joint": "ur5e_0_wrist_1",
        "ur5e_0_wrist_2_joint": "ur5e_0_wrist_2",
        "ur5e_0_wrist_3_joint": "ur5e_0_wrist_3",

        },
    all_link_names=[
        "ur5e_0_shoulder_link",
        "ur5e_0_upper_arm_link",
        "ur5e_0_forearm_link",
        "ur5e_0_wrist_1_link",
        "ur5e_0_wrist_2_link",
        "ur5e_0_wrist_3_link",
        "ur5e_0_robotiq_gripper",
        "robotiq_base_mount",
        "2f85_base",
        "right_driver",
        "right_spring_link",
        "right_pad",
        "right_follower",
        "right_coupler", 
        "left_driver",
        "left_spring_link",
        "left_pad", 
        "left_follower",
        "left_coupler", 
        ],
    arm_link_names=[
        "ur5e_0_shoulder_link",
        "ur5e_0_upper_arm_link",
        "ur5e_0_forearm_link",
        "ur5e_0_wrist_1_link",
        "ur5e_0_wrist_2_link",
        "ur5e_0_wrist_3_link", 
        ],
    ee_link_names=[
        "right_driver",
        "right_spring_link",
        "right_pad",
        "right_follower",
        "right_coupler", 
        "left_driver",
        "left_spring_link",
        "left_pad", 
        "left_follower",
        "left_coupler"
        ], 
    base_joint="ur5e_0_base_joint",
    ee_site_name="robotiq_ee",
    grasp_actuator="robotiq_fingers_actuator",
    weld_body_name="robotiq",
    mesh_to_geoms = {"robotiq_assets/base_mount.stl": ["base_mount_collision"],
                    "robotiq_assets/base.stl": ["base_collision"],
                    "robotiq_assets/driver.stl": ["right_driver_collision", "left_driver_collision"],
                    "robotiq_assets/coupler.stl": ["right_coupler_collision","left_coupler_collision"],
                    "robotiq_assets/spring_link.stl": ["right_spring_collision","left_spring_collision"],
                    "robotiq_assets/follower.stl": ["right_follower_collision", "left_follower_collision"]
                    },
)

UR5E_SUCTION_CONSTANTS=dict(
    name="ur5e_suction",
    all_joint_names=[
        "ur5e_1_shoulder_pan_joint",
        "ur5e_1_shoulder_lift_joint",
        "ur5e_1_elbow_joint",
        "ur5e_1_wrist_1_joint",
        "ur5e_1_wrist_2_joint",
        "ur5e_1_wrist_3_joint",
        "ur5e_1_base_joint",
        ],
    ik_joint_names=[
        "ur5e_1_shoulder_pan_joint",
        "ur5e_1_shoulder_lift_joint",
        "ur5e_1_elbow_joint",
        "ur5e_1_wrist_1_joint",
        "ur5e_1_wrist_2_joint",
        "ur5e_1_wrist_3_joint",
        "ur5e_1_base_joint",        
    ],
    arm_joint_names=[
        "ur5e_1_shoulder_pan_joint",
        "ur5e_1_shoulder_lift_joint",
        "ur5e_1_elbow_joint",
        "ur5e_1_wrist_1_joint",
        "ur5e_1_wrist_2_joint",
        "ur5e_1_wrist_3_joint", 
        ],
    actuator_info={
        "ur5e_1_shoulder_pan_joint": "ur5e_1_shoulder_pan",
        "ur5e_1_shoulder_lift_joint": "ur5e_1_shoulder_lift",
        "ur5e_1_elbow_joint": "ur5e_1_elbow",
        "ur5e_1_wrist_1_joint": "ur5e_1_wrist_1",
        "ur5e_1_wrist_2_joint": "ur5e_1_wrist_2",
        "ur5e_1_wrist_3_joint": "ur5e_1_wrist_3",
        "ur5e_1_base_joint": "ur5e_1_base",
        },
    all_link_names=[
        "ur5e_1_shoulder_link",
        "ur5e_1_upper_arm_link",
        "ur5e_1_forearm_link",
        "ur5e_1_wrist_1_link",
        "ur5e_1_wrist_2_link",
        "ur5e_1_wrist_3_link",
        "ur5e_1_suction_gripper",
        "suction_base",
        "suction_midLink",
        "suction_headLink",
        "suction_tipLink",
        "suction_disk",
        ],
    arm_link_names=[
        "ur5e_1_shoulder_link",
        "ur5e_1_upper_arm_link",
        "ur5e_1_forearm_link",
        "ur5e_1_wrist_1_link",
        "ur5e_1_wrist_2_link",
        "ur5e_1_wrist_3_link", 
        ],
    ee_link_names=["suction_headLink", "suction_tipLink", "suction_disk"],
    base_joint="ur5e_1_base_joint",
    ee_site_name="suction_ee",
    grasp_actuator="adhere_gripper",
    weld_body_name="suction",
)

PANDA_CONSTANTS=dict(
    name="panda",
    all_joint_names=[
        "panda_base_joint",
        "joint1",
        "joint2",
        "joint3",
        "joint4",
        "joint5",
        "joint6",
        "joint7",
        "finger_joint1",
        "finger_joint2",

        ],
    ik_joint_names=[
        "panda_base_joint",
        "joint1",
        "joint2",
        "joint3",
        "joint4",
        "joint5",
        "joint6",
        "joint7", 
    ],
    arm_joint_names=[
        "joint1",
        "joint2",
        "joint3",
        "joint4",
        "joint5",
        "joint6",
        "joint7",
        ],
    actuator_info={
        "panda_base_joint":"panda_base",
        "joint1": "actuator1",
        "joint2": "actuator2",
        "joint3": "actuator3",
        "joint4": "actuator4",
        "joint5": "actuator5",
        "joint6": "actuator6",
        "joint7": "actuator7",
        "split": "actuator8",
    },
    mesh_to_geoms = {
        "assets/link0.stl": ["link0_collision"],
        "assets/link1.stl": ["link1_collision"],
        "assets/link2.stl": ["link2_collision"],
        "assets/link3.stl": ["link3_collision"],
        "assets/link4.stl": ["link4_collision"],
        "assets/link5_collision_0.obj": ["link5_collision_0"],
        "assets/link5_collision_1.obj": ["link5_collision_1"],
        "assets/link5_collision_2.obj": ["link5_collision_2"],
        "assets/link6.stl": ["link6_collision"],
        "assets/link7.stl": ["link7_collision"],
        "assets/hand.stl": ["hand_collision"],
        "assets/finger_0.obj": ["left_finger_0_collision","right_finger_0_collision"],
    },
    grasp_actuator="panda_gripper_actuator",
    all_link_names=[
        "",
        "link0",
        "link1",
        "link2",
        "link3",
        "link4",
        "link5",
        "link6",
        "link7",
        "hand",
        "left_finger",
        "right_finger",
        ],
    arm_link_names=[
        "",
        "link0",
        "link1",
        "link2",
        "link3",
        "link4",
        "link5",
        "link6",
        "link7",
        ],
    ee_link_names=["hand", "left_finger", "right_finger"],
    base_joint="panda_base_joint",
    ee_site_name="ee",
    weld_body_name="panda",
)


KINOVA_CONSTANTS=dict(
    name="kinovagen3",
    all_joint_names=[
        "base_joint",
        "joint_1",
        "joint_2",
        "joint_3",
        "joint_4",
        "joint_5",
        "joint_6",
        "joint_7",
        #Fixed Joints
        "joint_0",
        "end_effector", 
        "tool_frame_joint",
        "gripper_base_joint",
        "finger_joint",
        "left_outer_finger_joint",
        "left_inner_knuckle_joint",
        "left_inner_finger_joint",
        "left_inner_finger_pad_joint",
        "right_outer_knuckle_joint",
        "right_outer_finger_joint",
        "right_inner_knuckle_joint",
        "right_inner_finger_joint",
        "right_inner_finger_pad_joint"
    ],
    ik_joint_names=[
        "base_joint",
        "joint_1",
        "joint_2",
        "joint_3",
        "joint_4",
        "joint_5",
        "joint_6",
        "joint_7",
    ],
    arm_joint_names=[
        "joint_1",
        "joint_2",
        "joint_3",
        "joint_4",
        "joint_5",
        "joint_6",
        "joint_7",
        ],
    actuator_info={
        "base_joint":"base_actuator",
        "joint1": "actuator1",
        "joint2": "actuator2",
        "joint3": "actuator3",
        "joint4": "actuator4",
        "joint5": "actuator5",
        "joint6": "actuator6",
        "joint7": "actuator7",
        # "split": "actuator8",
    },
    grasp_actuator="gripper_actuator",
    all_link_names=[
        "mobile_base_link",
        "kinova_base_link",
        "shoulder_link",
        "half_arm_1_link",
        "half_arm_2_link",
        "forearm_link",
        "spherical_wrist_1_link",
        "spherical_wrist_2_link",
        "bracelet_link",
        "end_effector_link",
        "tool_frame",
        "robotiq_arg2f_base_link",
        "left_outer_knuckle",
        "left_outer_finger",
        "left_inner_finger",
        "left_inner_finger_pad",
        "left_inner_knuckle",
        "right_outer_knuckle",
        "right_outer_finger",
        "right_inner_finger",
        "right_inner_finger_pad",
        "right_inner_knuckle"
        ],
    arm_link_names=[
        "shoulder_link",
        "half_arm_1_link",
        "half_arm_2_link",
        "forearm_link",
        "spherical_wrist_1_link",
        "spherical_wrist_2_link",
        "bracelet_link",
        "end_effector_link",
        ],
    ee_link_names=["bracelet_link"],
    base_joint="base_joint",
    ee_site_name="ee",
    weld_body_name="kinovagen3",
)






























HUMANOID_CONSTANTS=dict(
    name="humanoid",
    all_joint_names=[
        "human_base_joint",
        "thoraxry",
        "thoraxrx",
        "rclaviclery",
        "rclaviclerz",
        "rhumerusrx",
        "rhumerusry",
        "rhumerusrz", 
        "rradiusrx",
        "rwristry", 
        "rhandrx",
        "rhandrz",
        "rfingersrx",
        "rthumbrx",
        "rthumbrz",   
    ],
    ik_joint_names=[
        "human_base_joint",
        "thoraxry",
        "thoraxrx",
        "rclaviclery",
        "rclaviclerz",
        "rhumerusrx",
        "rhumerusry",
        "rhumerusrz", 
        "rradiusrx",
        "rwristry", 
        "rhandrx",
        "rhandrz",    
    ],
    arm_joint_names=[
        "thoraxry",
        "thoraxrz",
        "rclaviclery",
        "rclaviclerz",
        "rhumerusrx",
        "rhumerusry",
        "rhumerusrz", 
        "rradiusrx",
        "rwristry", 
        "rhandrx",
        "rhandrz",    
        ],
    actuator_info={
        "human_base_joint": "human_base",
        "rhumerusrx": "rhumerusrx",
        "rhumerusry": "rhumerusry",
        "rhumerusrz": "rhumerusrz",
        "rclaviclery": "rclaviclery",
        "rclaviclerz": "rclaviclerz",
        "rradiusrx": "rradiusrx",
        "rhandrx": "rhandrx",
        "rhandrz": "rhandrz",
        "rwristry": "rwristry",
        "rfingersrx": "rfingersrx",
        "thoraxrx": "thoraxrx",
        "thoraxry": "thoraxry",
        "thoraxrz": "thoraxrz",
        "rthumbrx": "rthumbrx",
        "rthumbrz": "rthumbrz", 
        "fingers": ["rfingersrx", "rthumbrz"],
        },
    grasp_actuator="adhere_hand",
    all_link_names=[
        "lowerback",
        "upperback",
        "thorax",
        "lowerneck",
        "upperneck",
        "head",
        "lclavicle",
        "lhumerus",
        "lradius",
        "lhand",
        "lfingers",
        "lthumb",
        "rclavicle",
        "rhumerus",
        "rradius",
        "rhand",
        "rfingers",
        "rpalm",
        "rthumb",
        ],
    arm_link_names=[
        "upperback",
        "thorax",
        "lowerneck",
        "upperneck",
        "head",
        "rclavicle",
        "rhumerus",
        "rradius",
        "rhand",
        ],
    ee_link_names=["rhand", "rfingers", "rthumb","rpalm"],
    # keypoint_site_names=[
    #     name+"_keyp" for name in ["head_top", "head", "rhumerus", "rradius", "rhand", "lhumerus", "lradius", "lhand"]
    #     ],
    base_joint="human_base_joint",
    ee_site_name="right_hand_site",
    weld_body_name="rpalm",
)
HUMANOID_LEFT_BODY_NAMES=[
    "lclavicle",
    "lhumerus",
    "lradius",
    "lwrist",
    "lhand",
    "lfingers",
    "lthumb",
]
TABLE_GRID_POS = [
    dict(pos=[0.05, 0.3, 0.3], size=[0.08, 0.05, 0.01]),
    dict(pos=[0.05, 0.5, 0.3], size=[0.08, 0.08, 0.01]),
    dict(pos=[0.05, 0.7, 0.3], size=[0.08, 0.05, 0.01]),

    dict(pos=[0.3, 0.3, 0.3], size=[0.08, 0.05, 0.01]),
    dict(pos=[0.3, 0.5, 0.3], size=[0.08, 0.08, 0.01]),
    dict(pos=[0.3, 0.7, 0.3], size=[0.08, 0.05, 0.01]),

    dict(pos=[0.55, 0.3, 0.3], size=[0.08, 0.05, 0.01]),
    dict(pos=[0.55, 0.5, 0.3], size=[0.08, 0.08, 0.01]),
    dict(pos=[0.55, 0.7, 0.3], size=[0.08, 0.05, 0.01]),

    dict(pos=[0.8, 0.3, 0.3], size=[0.08, 0.05, 0.01]),
    dict(pos=[0.8, 0.5, 0.3], size=[0.08, 0.08, 0.01]),
    dict(pos=[0.8, 0.7, 0.3], size=[0.08, 0.05, 0.01]),
]
BIN_GRID_POS = [
    # inside the bin, left side
    dict(pos=[-0.65, 0.68, 0.3], size=[0.1, 0.05, 0.01]),
    dict(pos=[-0.65, 0.5, 0.3], size=[0.1, 0.05, 0.01]),
    dict(pos=[-0.65, 0.32, 0.3], size=[0.1, 0.05, 0.01]),
    # inside the bin, right side
    dict(pos=[-0.38, 0.68, 0.3], size=[0.1, 0.05, 0.01]),
    dict(pos=[-0.38, 0.5, 0.3], size=[0.1, 0.05, 0.01]),
    dict(pos=[-0.38, 0.32, 0.3], size=[0.1, 0.05, 0.01]),
]
BIN_GRID_POS=BIN_GRID_POS[0:1]+BIN_GRID_POS[3:4]
SCENE_BOUNDS=((-1.4, -0.2, -0.1), (1.7, 1.2, 1.1))

HUMAN_KEYPOINT_SITE_NAMES = [name+"_keyp" for \
    name in ["head_top", "head", "rhumerus", "rradius", "rhand", "lhumerus", "lradius", "lhand"]]

 
